# Generated by Django 3.0.1 on 2020-08-25 13:59

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1080], upload_to='images/'),
        ),
    ]
