# Generated by Django 3.0.1 on 2020-08-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200825_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introtext',
            field=models.CharField(default='ABCD', max_length=300),
        ),
    ]
