# Generated by Django 3.0.1 on 2020-08-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_introtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.TextField(choices=[('travel', 'Travel'), ('languages', 'Languages'), ('teaching', 'Teaching'), ('miscellaneous', 'Miscellaneous')], default='Miscellaneous'),
        ),
    ]
