# Generated by Django 3.0.1 on 2020-12-03 21:45

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.TextField(choices=[('Travel', 'Travel'), ('Languages', 'Languages'), ('Teaching', 'Teaching'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous'),
        ),
    ]
