# Generated by Django 3.0.1 on 2020-12-04 22:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20201203_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[1920, 1080], upload_to='images/'),
        ),
    ]
